import type { ResolvedHubConfig } from "../config.js";

export function pageCopySource(config: ResolvedHubConfig): string {
  return `import type { BreadcrumbItem } from "@learning-platform/ui";
import type { PageContext } from "./page-context";

export function pageHeader(context: PageContext): { title: string; subtitle: string } {
  switch (context.page) {
    case "learning":
      return { title: "Weeks", subtitle: "Weekly learning routes. Curriculum is not generated by the CLI." };
    case "week-1":
      return { title: "Week 1", subtitle: "Placeholder week shell. Author sessions and activities before learners use this page." };
    case "foundations":
      return { title: "Foundations", subtitle: "Placeholder phase shell. Author tasks before learners use this page." };
    case "task-1":
      return { title: "Task 1", subtitle: "Placeholder task shell. No assessment content is generated." };
    case "assignments":
      return { title: "Assignments", subtitle: "Placeholder assignment workspace. The hub does not award grades." };
    case "project":
      return { title: "Project", subtitle: "Placeholder project workspace." };
    case "resources":
      return { title: "Resources", subtitle: "Shared reference material. Teaching activities belong on learning pages." };
    case "help":
      return { title: "Help", subtitle: "How to move around this hub and use a learner account." };
    case "account":
      return { title: "Learner account", subtitle: "Sign in or create an account to use learner-specific platform features." };
    default:
      return { title: ${JSON.stringify(config.displayName)}, subtitle: ${JSON.stringify(config.qualification)} };
  }
}

export function breadcrumbs(context: PageContext): BreadcrumbItem[] {
  const home = { label: "Home", href: "" };
  if (context.page === "home") return [home];
  if (context.page === "week-1") {
    return [home, { label: "Weeks", href: "weeks/" }, { label: "Week 1" }];
  }
  const labels: Record<string, string> = {
    learning: "Weeks",
    resources: "Resources",
    help: "Help",
    account: "Account",
    foundations: "Foundations",
    "task-1": "Task 1",
    assignments: "Assignments",
    project: "Project"
  };
  return [home, { label: labels[context.page] || context.page }];
}
`;
}

export function pagesSource(config: ResolvedHubConfig): string {
  const weekImports = config.profile === "week-based"
    ? `import { EmptyState, WeekView } from "@learning-platform/ui";\n`
    : `import { EmptyState } from "@learning-platform/ui";\n`;
  const contentHook = config.useContentEngine && config.profile === "week-based"
    ? `import { useContentPackage } from "../content/useContentPackage";\n`
    : "";

  const weekPages = config.profile === "week-based" ? `
export function WeeksPage({ root }: { root: string }) {
  ${config.useContentEngine ? `const { weeks, loading } = useContentPackage(root);
  if (loading) return <p>Loading weeks</p>;
  if (!weeks.length) {
    return (
      <EmptyState
        heading="No weeks authored yet"
        message="This hub is week-based. Add weeks to the content package when curriculum is ready."
      />
    );
  }
  return (
    <div className="card-grid">
      {weeks.map((week) => (
        <article className="hub-card" key={week.weekKey}>
          <h2>Week {week.teachingWeek}</h2>
          <p>{week.title}</p>
          <a className="card-link" href={\`\${root}/\${week.route}\`}>Open Week {week.teachingWeek}</a>
        </article>
      ))}
    </div>
  );` : `return (
    <EmptyState
      heading="Weekly learning"
      message="This is a week-based hub shell. Author Week 1 before adding more weeks."
      action={{ label: "Open Week 1 placeholder", href: \`\${root}/weeks/week-1/\` }}
    />
  );`}
}

export function WeekPlaceholderPage() {
  return (
    <WeekView
      week={{
        id: "week-1",
        teachingWeek: 1,
        title: "Week 1",
        status: "planned",
        emptyMessage: "No sessions or activities have been authored yet."
      }}
      sessions={[]}
      features={{
        showLearningOutcomes: ${config.profile === "week-based" ? "true" : "false"},
        showAssignmentContext: ${config.contextType === "assignment" ? "true" : "false"},
        showExamContext: ${config.contextType === "exam" ? "true" : "false"},
        showProjectContext: ${config.contextType === "project" ? "true" : "false"}
      }}
    />
  );
}
` : "";

  const taskPages = config.profile === "task-based" ? `
export function FoundationsPage({ root }: { root: string }) {
  return (
    <EmptyState
      heading="Foundations"
      message="This is a task-based hub shell. Author foundation activities in this hub; they are not generated."
      action={{ label: "Open Task 1 placeholder", href: \`\${root}/task-1/\` }}
    />
  );
}

export function TaskPage() {
  return (
    <EmptyState
      heading="Task 1"
      message="Placeholder task route. Do not treat this page as an assessment."
    />
  );
}
` : "";

  const extraPages = `
export function AssignmentsPage() {
  return (
    <EmptyState
      heading="Assignments"
      message="Placeholder assignment workspace. The hub organises evidence later; it does not award grades."
    />
  );
}

export function ProjectPage() {
  return (
    <EmptyState
      heading="Project"
      message="Placeholder project workspace. Author the project journey before learners rely on this page."
    />
  );
}
`;

  return `${weekImports}${contentHook}import { createSitePath } from "../paths";

export function HomePage({ root }: { root: string }) {
  return (
    <section className="panel" aria-labelledby="welcome-heading">
      <h2 id="welcome-heading">Welcome</h2>
      <p>${escapeJs(config.displayName)} is a Learning Platform learner hub. Teaching pages are readable without signing in. Sign in from Account when you need learner context, onboarding or submissions.</p>
      <p>This scaffold contains platform structure only. Curriculum, assessments and subject content are not generated.</p>
      <p><a className="text-link" href={createSitePath(root, "resources/")}>Open resources</a></p>
    </section>
  );
}

export function ResourcesPage() {
  return (
    <section className="panel">
      <h2>Resources</h2>
      <p>Add approved learner resources here. Do not copy teaching content from another hub.</p>
    </section>
  );
}

export function HelpPage({ root }: { root: string }) {
  return (
    <section className="panel">
      <h2>How to navigate</h2>
      <ul>
        <li>Use Home for the starting point.</li>
        <li>Open <a href={\`\${root}/resources/\`}>Resources</a> for shared reference material.</li>
        <li>Open <a href={\`\${root}/account/\`}>Account</a> to sign in or register.</li>
        <li>On a smaller screen, use the Menu button.</li>
      </ul>
      <h2>Account and progress</h2>
      <p>Teaching pages remain readable without an account. Progress, enrolment and submissions require authentication. Passwords are sent only to Supabase Auth.</p>
    </section>
  );
}

export function AccountPage() {
  return (
    <section className="panel">
      <h2>Sign in or register</h2>
      <p>Use the Sign in control in the header. The shared Learning Platform account dialog handles sign in, registration and onboarding.</p>
    </section>
  );
}
${weekPages}${taskPages}${extraPages}
`;
}

export function appSource(config: ResolvedHubConfig): string {
  const extraImports = [
    config.profile === "week-based" ? `import { WeekPlaceholderPage, WeeksPage } from "./pages/HubPages";` : "",
    config.profile === "task-based" ? `import { FoundationsPage, TaskPage } from "./pages/HubPages";` : "",
    config.contextType === "assignment" && config.profile !== "minimal" ? `import { AssignmentsPage } from "./pages/HubPages";` : "",
    config.contextType === "project" && config.profile !== "minimal" ? `import { ProjectPage } from "./pages/HubPages";` : ""
  ].filter(Boolean).join("\n");

  const extraBody = [
    config.profile === "week-based" ? `  if (context.page === "learning") return <WeeksPage root={context.root} />;
  if (context.view === "week" || context.page === "week-1") return <WeekPlaceholderPage />;` : "",
    config.profile === "task-based" ? `  if (context.page === "foundations") return <FoundationsPage root={context.root} />;
  if (context.page === "task-1") return <TaskPage />;` : "",
    config.contextType === "assignment" && config.profile !== "minimal" ? `  if (context.page === "assignments") return <AssignmentsPage />;` : "",
    config.contextType === "project" && config.profile !== "minimal" ? `  if (context.page === "project") return <ProjectPage />;` : ""
  ].filter(Boolean).join("\n");

  return `import { HubShell, LearnerHeader } from "@learning-platform/ui";
import { APP_CONFIG } from "./config";
import { useHubPlatform } from "./hooks/useHubPlatform";
import { currentIds, type PageContext } from "./page-context";
import { breadcrumbs, pageHeader } from "./page-copy";
import { AccountPage, HelpPage, HomePage, ResourcesPage } from "./pages/HubPages";
${extraImports}
import { createSitePath, navigationItems } from "./paths";

function PageBody({ context }: { context: PageContext }) {
${extraBody}
  if (context.page === "resources") return <ResourcesPage />;
  if (context.page === "help") return <HelpPage root={context.root} />;
  if (context.page === "account") return <AccountPage />;
  return <HomePage root={context.root} />;
}

export function App({ context }: { context: PageContext }) {
  const { learner, theme, accountDialog, platform } = useHubPlatform(context.root);
  const header = pageHeader(context);

  return (
    <HubShell
      brandTitle={APP_CONFIG.shortName}
      brandTagline={APP_CONFIG.qualification}
      navigation={navigationItems([...APP_CONFIG.navigation], context.root)}
      currentId={context.section}
      currentIds={currentIds(context)}
      theme={theme}
      actions={(
        <div className="student-account" data-student-account="">
          {learner ? (
            <>
              <span className="student-account__name">{learner.displayName || learner.fullName || "Learner"}</span>
              <button
                className="lp-button lp-button--secondary"
                type="button"
                onClick={(event) => accountDialog?.open(event.currentTarget)}
              >
                Account
              </button>
            </>
          ) : (
            <button
              className="lp-button lp-button--secondary"
              type="button"
              onClick={(event) => accountDialog?.open(event.currentTarget)}
            >
              Sign in
            </button>
          )}
        </div>
      )}
      breadcrumbs={breadcrumbs(context)}
      resolveHref={(path) => createSitePath(context.root, path)}
      pageHeader={header}
      learnerHeader={(
        <LearnerHeader
          learner={learner}
          hubName={platform.config.hubName}
          accountHref={platform.config.accountPath}
          onSignOut={() => platform.auth.signOut()}
        />
      )}
      footer={{
        lines: [
          APP_CONFIG.siteName,
          APP_CONFIG.qualification,
          APP_CONFIG.currentPhase
        ]
      }}
    >
      <PageBody context={context} />
    </HubShell>
  );
}
`;
}

function escapeJs(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll("`", "\\`").replaceAll("${", "\\${");
}
